### ISSUE TITLE
Bussjob error after 2 rounds of buss driving

### ISSUE THREAD

**Issue by Skillgjii** [qbcore-framework/qb-busjob#10]
if you do 2 rounds of the bus job, and then go back to deliver the buss. Then you try to take out a new buss you will get this error. 
The Gps locations will also stop showing. 
https://gyazo.com/5c2ad3803165cef87915f55c092a9c9c

**Comment by GeekHamza1** [comment]
same here

**Comment by dwiprizzy** [comment]
Any update for this error ?

**Comment by coba59** [comment]
here the fix bros.
https://github.com/qbcore-framework/qb-busjob/issues/18
