### ISSUE TITLE
I can convert it to QB

### ISSUE THREAD

**Issue by jnccloud** [qbcore-framework/qb-busjob#2]
I've noticed it's been here for a while. I don't mind using this as my first full conversion script - I need the experience anyway. Does anyone have any plans for it otherwise?

**Comment by zfbx** [comment]
taking a quick look through, it might not be worth it, might be better to remake from scratch.

**Comment by jnccloud** [comment]
That's basically what would probably happen. I was figuring a conversion to see what the functionality is supposed to look and feel like and then a complete remake to get it up to par. This community has provided so much for me I figured this could be a small way to help out everyone else and learn some more in the process. And since it's an unused resource right now, where else is a better place to make a huge mistake?! haha.
