### ISSUE TITLE
JOB ISSUES

### ISSUE THREAD

**Issue by Motofam** [qbcore-framework/qb-busjob#30]
when you log in if you have the garbage job, the npc does not show up unless you go and get the job again or restart the script, also getting a attempt o index nil value (field 'job') this is with updated qb-core
![unknown](https://user-images.githubusercontent.com/100702772/162119854-e8c12bfe-f643-40d5-bf72-e58c0df6301f.png)

**Comment by erpofficial** [comment]
![image](https://user-images.githubusercontent.com/102900480/162747869-49a366fe-055c-4686-944a-1b22f1553c81.png)
same issue !

**Comment by erpofficial** [comment]
Did you get any fix ??????

**Comment by oosayeroo** [comment]
i am having the same issue with busjob. been tring to play around the it but cant seem to fix it

**Comment by subhampro** [comment]
> 

if you get a fix please share with us

**Comment by Tomboru** [comment]
> > 
> 
> if you get a fix please share with us

Gonna look into it.
How to replicate?

**Comment by erikmeyer08** [comment]
I'm experiencing the same issue. I get the exception when loading into the server.

**Comment by kevintransp** [comment]
I'm also experience this issue with
`SCRIPT ERROR: @qb-busjob/client/main.lua:276: attempt to index a nil value (field 'job')`

**Comment by Tomboru** [comment]
> I'm also experience this issue with `SCRIPT ERROR: @qb-busjob/client/main.lua:276: attempt to index a nil value (field 'job')`
> 
> replicate i'm getting this error after loading in. Doesn't matter witch job you have or if you are in or out the polyzone every body get this error.

Did you update to the newest core update?

**Comment by kevintransp** [comment]
No i did not run on newest core

**Comment by tom-osborne** [comment]
@Motofam @erpofficial @oosayeroo @subhampro @erikmeyer08 @kevintransp 

Could you all please update to the latest version and re-test? I believe these issues are now fixed.

Thanks

**Comment by tom-osborne** [comment]
@Motofam @erpofficial @oosayeroo @subhampro @erikmeyer08 @kevintransp 

Could you all please update to the latest version and re-test? I believe these issues are now fixed.

Thanks

**Comment by kevintransp** [comment]
Can not do that, core is to different so i have to upgrade al the scripts.

**Comment by FjamZoo** [comment]
All the issues has been fixed regarding this particular please update to latest version and core, if you see the issue stated above happening again feel free to remake the issue Thanks.
