### ISSUE TITLE
qb-busjob will not start

### ISSUE THREAD

**Issue by ronhillgaming** [qbcore-framework/qb-busjob#32]
When we try to go to the bus depot to start the job, the menu never appears where it supposed to. F8 shows this error: 
if Player.job.name == "bus" then

Shared/jobs.lua shows "bus" established as a job. /job for player shows "Bus grade driver duty true". I just can't figure out what is causing this error. Thanks.

**Comment by NotReloads** [comment]
remove the .name

**Comment by tom-osborne** [comment]
> When we try to go to the bus depot to start the job, the menu never appears where it supposed to. F8 shows this error: if Player.job.name == "bus" then
> 
> Shared/jobs.lua shows "bus" established as a job. /job for player shows "Bus grade driver duty true". I just can't figure out what is causing this error. Thanks.

Hi @ronhillgaming, please could you try with the current latest version of the script?
