### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by balcer64** [qbcore-framework/qb-busjob#8]
players can take an infinite number of cars without collateral, as on garbage trucks, in practice 7-10 players completely blocked traffic in the city, if players have such an opportunity, they will definitely take advantage of it
![screenshot40](https://user-images.githubusercontent.com/22128071/145710508-b1e0dd61-67fa-457a-ad83-9dee10ae7795.png)

**Comment by balcer64** [comment]
after working on the bus, I got a job in a taxi, the route remained from the bus
![screenshot43](https://user-images.githubusercontent.com/22128071/145710536-b9e382f4-1349-46ec-9412-56704978b160.png)

**Comment by fpaiva36834** [comment]
Fixed the too, is just set that the script know's if the user has picked up a bus previusly or not.
Problem if he blow's up his bus or loses it he can't get another, only if he relogs
